Revert "fix(TESB-22833):CI builder NoClassDefFoundError error with routelet (#313)" (#315)
This reverts commit 1e8dc126710fdf53af969e74a35f0c520e775a67.